# Generated by Django 3.0.7 on 2020-06-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('Race', 'Race'), ('Training Session', 'Training Session')], max_length=64)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
    ]
