# Generated by Django 3.0.6 on 2020-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicRun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(blank=True),
        ),
    ]
