# Generated by Django 3.0.6 on 2020-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicRun', '0002_auto_20200528_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_uri',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
