# Generated by Django 3.0.6 on 2020-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicRun', '0003_auto_20200604_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='song',
            name='danceability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(default=0),
        ),
    ]
