# Generated by Django 3.0.6 on 2020-06-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicRun', '0006_spotifyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='songs',
            field=models.ManyToManyField(blank=True, to='musicRun.Song'),
        ),
    ]
